### ISSUE TITLE
moveTo is expecting a game object, not a body

### ISSUE THREAD

**Issue by saricden** [yandeu/arcade-physics#2]
Fantastic library @yandeu , it has helped me so much to integrate physics into authoritative multiplayer servers leveraging with clients that leverage Phaser 3.

Small bug I noted:

Calling the `moveTo` function looks as though it's still expecting a Phaser GameObject, not a Body.

If you take a look at `arcade-physics/lib/physics/arcade/ArcadePhysics.js:437` you'll see it's looking at `gameObject.body.velocity...`, whereas I would expect it to work with just a Body (as gameObjects do not exist in this pure physics implementation).

If you'd like I'd be happy to submit a PR to fix. Please let me know.

All the best,
Kirk

**Comment by yandeu** [comment]
Thanks!

Yeah, I haven't converted all functions yet. There are still a lot of things missing. 

Yes, would be nice if you could make a PR. And maybe write a test for it?

**Comment by yandeu** [comment]
I have implemented it. I will be available in the next release :)
